# This workflow will do a clean install of node dependencies, build the source code, then push changes direct to master.

name: Build & Push Blocks

on:
  push:
    branches: 
    - master

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build production blocks CSS and Javascript files.
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      run: npm ci
      run: npm run build
    - name: Push production files to master.
      run: |
          git config --global user.name 'young295'
          git config --global user.email 'young295@purdue.edu'
          git commit -am "Automated build"
          git push
